### PR TITLE
 commit 25.02.2019 homework

### PR DESCRIPTION
**Pull request by MateAcademy**

### CODE REVIEW

**Comment by un-install** [comment]
where is Customers?

**Review by un-install — COMMENTED** [review]
?

**Review by SerhiiPasko — CHANGES_REQUESTED** [review]
Not full homeWork

**Review by SerhiiPasko — CHANGES_REQUESTED** [review]
@ManyToOne(fetch = FetchType.LAZY), @JoinColumn(name = "CUST_REP"). What is it?

**Pull request merged**
